// <auto-generated />
namespace K9.DataAccessLayer.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EmailQueueController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailQueueController));
        
        string IMigrationMetadata.Id
        {
            get { return "202502260614229_EmailQueueController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
