// <auto-generated />
namespace K9.DataAccessLayer.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MailingsListsEmailTempltes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MailingsListsEmailTempltes));
        
        string IMigrationMetadata.Id
        {
            get { return "202502190118440_MailingsListsEmailTempltes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
