// <auto-generated />
namespace K9.DataAccessLayer.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddViewCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddViewCount));
        
        string IMigrationMetadata.Id
        {
            get { return "202512161533220_AddViewCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
