
using System.Data.Entity.Migrations;
using System.Linq;
using K9.DataAccess.Models;

namespace K9.DataAccess.Database
{
	public partial class DatabaseInitialiser : DbMigrationsConfiguration<Db>
	{

		private void SeedCountries(Db context)
		{
			if (context.Countries.Count() == 0)
			{
				context.Countries.AddOrUpdate(new Country { Name = "Afghanistan", TwoLetterCountryCode = "AF", ThreeLetterCountryCode = "AFG" });
				context.Countries.AddOrUpdate(new Country { Name = "Albania", TwoLetterCountryCode = "AL", ThreeLetterCountryCode = "ALB" });
				context.Countries.AddOrUpdate(new Country { Name = "Algeria", TwoLetterCountryCode = "DZ", ThreeLetterCountryCode = "DZA" });
				context.Countries.AddOrUpdate(new Country { Name = "American Samoa", TwoLetterCountryCode = "AS", ThreeLetterCountryCode = "ASM" });
				context.Countries.AddOrUpdate(new Country { Name = "Andorra", TwoLetterCountryCode = "AD", ThreeLetterCountryCode = "AND" });
				context.Countries.AddOrUpdate(new Country { Name = "Angola", TwoLetterCountryCode = "AO", ThreeLetterCountryCode = "AGO" });
				context.Countries.AddOrUpdate(new Country { Name = "Anguilla", TwoLetterCountryCode = "AI", ThreeLetterCountryCode = "AIA" });
				context.Countries.AddOrUpdate(new Country { Name = "Antarctica", TwoLetterCountryCode = "AQ", ThreeLetterCountryCode = "ATA" });
				context.Countries.AddOrUpdate(new Country { Name = "Antigua And Barbuda", TwoLetterCountryCode = "AG", ThreeLetterCountryCode = "ATG" });
				context.Countries.AddOrUpdate(new Country { Name = "Argentina", TwoLetterCountryCode = "AR", ThreeLetterCountryCode = "ARG" });
				context.Countries.AddOrUpdate(new Country { Name = "Armenia", TwoLetterCountryCode = "AM", ThreeLetterCountryCode = "ARM" });
				context.Countries.AddOrUpdate(new Country { Name = "Aruba", TwoLetterCountryCode = "AW", ThreeLetterCountryCode = "ABW" });
				context.Countries.AddOrUpdate(new Country { Name = "Australia", TwoLetterCountryCode = "AU", ThreeLetterCountryCode = "AUS" });
				context.Countries.AddOrUpdate(new Country { Name = "Austria", TwoLetterCountryCode = "AT", ThreeLetterCountryCode = "AUT" });
				context.Countries.AddOrUpdate(new Country { Name = "Azerbaijan", TwoLetterCountryCode = "AZ", ThreeLetterCountryCode = "AZE" });
				context.Countries.AddOrUpdate(new Country { Name = "Bahamas", TwoLetterCountryCode = "BS", ThreeLetterCountryCode = "BHS" });
				context.Countries.AddOrUpdate(new Country { Name = "Bahrain", TwoLetterCountryCode = "BH", ThreeLetterCountryCode = "BHR" });
				context.Countries.AddOrUpdate(new Country { Name = "Bangladesh", TwoLetterCountryCode = "BD", ThreeLetterCountryCode = "BGD" });
				context.Countries.AddOrUpdate(new Country { Name = "Barbados", TwoLetterCountryCode = "BB", ThreeLetterCountryCode = "BRB" });
				context.Countries.AddOrUpdate(new Country { Name = "Belarus", TwoLetterCountryCode = "BY", ThreeLetterCountryCode = "BLR" });
				context.Countries.AddOrUpdate(new Country { Name = "Belgium", TwoLetterCountryCode = "BE", ThreeLetterCountryCode = "BEL" });
				context.Countries.AddOrUpdate(new Country { Name = "Belize", TwoLetterCountryCode = "BZ", ThreeLetterCountryCode = "BLZ" });
				context.Countries.AddOrUpdate(new Country { Name = "Benin", TwoLetterCountryCode = "BJ", ThreeLetterCountryCode = "BEN" });
				context.Countries.AddOrUpdate(new Country { Name = "Bermuda", TwoLetterCountryCode = "BM", ThreeLetterCountryCode = "BMU" });
				context.Countries.AddOrUpdate(new Country { Name = "Bhutan", TwoLetterCountryCode = "BT", ThreeLetterCountryCode = "BTN" });
				context.Countries.AddOrUpdate(new Country { Name = "Bolivia", TwoLetterCountryCode = "BO", ThreeLetterCountryCode = "BOL" });
				context.Countries.AddOrUpdate(new Country { Name = "Bosnia And Herzegowina", TwoLetterCountryCode = "BA", ThreeLetterCountryCode = "BIH" });
				context.Countries.AddOrUpdate(new Country { Name = "Botswana", TwoLetterCountryCode = "BW", ThreeLetterCountryCode = "BWA" });
				context.Countries.AddOrUpdate(new Country { Name = "Bouvet Island", TwoLetterCountryCode = "BV", ThreeLetterCountryCode = "BVT" });
				context.Countries.AddOrUpdate(new Country { Name = "Brazil", TwoLetterCountryCode = "BR", ThreeLetterCountryCode = "BRA" });
				context.Countries.AddOrUpdate(new Country { Name = "British Indian Ocean Territory", TwoLetterCountryCode = "IO", ThreeLetterCountryCode = "IOT" });
				context.Countries.AddOrUpdate(new Country { Name = "Brunei Darussalam", TwoLetterCountryCode = "BN", ThreeLetterCountryCode = "BRN" });
				context.Countries.AddOrUpdate(new Country { Name = "Bulgaria", TwoLetterCountryCode = "BG", ThreeLetterCountryCode = "BGR" });
				context.Countries.AddOrUpdate(new Country { Name = "Burkina Faso", TwoLetterCountryCode = "BF", ThreeLetterCountryCode = "BFA" });
				context.Countries.AddOrUpdate(new Country { Name = "Burundi", TwoLetterCountryCode = "BI", ThreeLetterCountryCode = "BDI" });
				context.Countries.AddOrUpdate(new Country { Name = "Cambodia", TwoLetterCountryCode = "KH", ThreeLetterCountryCode = "KHM" });
				context.Countries.AddOrUpdate(new Country { Name = "Cameroon", TwoLetterCountryCode = "CM", ThreeLetterCountryCode = "CMR" });
				context.Countries.AddOrUpdate(new Country { Name = "Canada", TwoLetterCountryCode = "CA", ThreeLetterCountryCode = "CAN" });
				context.Countries.AddOrUpdate(new Country { Name = "Cape Verde", TwoLetterCountryCode = "CV", ThreeLetterCountryCode = "CPV" });
				context.Countries.AddOrUpdate(new Country { Name = "Cayman Islands", TwoLetterCountryCode = "KY", ThreeLetterCountryCode = "CYM" });
				context.Countries.AddOrUpdate(new Country { Name = "Central African Republic", TwoLetterCountryCode = "CF", ThreeLetterCountryCode = "CAF" });
				context.Countries.AddOrUpdate(new Country { Name = "Chad", TwoLetterCountryCode = "TD", ThreeLetterCountryCode = "TCD" });
				context.Countries.AddOrUpdate(new Country { Name = "Chile", TwoLetterCountryCode = "CL", ThreeLetterCountryCode = "CHL" });
				context.Countries.AddOrUpdate(new Country { Name = "China", TwoLetterCountryCode = "CN", ThreeLetterCountryCode = "CHN" });
				context.Countries.AddOrUpdate(new Country { Name = "Christmas Island", TwoLetterCountryCode = "CX", ThreeLetterCountryCode = "CXR" });
				context.Countries.AddOrUpdate(new Country { Name = "Cocos (Keeling) Islands", TwoLetterCountryCode = "CC", ThreeLetterCountryCode = "CCK" });
				context.Countries.AddOrUpdate(new Country { Name = "Colombia", TwoLetterCountryCode = "CO", ThreeLetterCountryCode = "COL" });
				context.Countries.AddOrUpdate(new Country { Name = "Comoros", TwoLetterCountryCode = "KM", ThreeLetterCountryCode = "COM" });
				context.Countries.AddOrUpdate(new Country { Name = "Congo", TwoLetterCountryCode = "CG", ThreeLetterCountryCode = "COG" });
				context.Countries.AddOrUpdate(new Country { Name = "Congo, The Drc", TwoLetterCountryCode = "CD", ThreeLetterCountryCode = "COD" });
				context.Countries.AddOrUpdate(new Country { Name = "Cook Islands", TwoLetterCountryCode = "CK", ThreeLetterCountryCode = "COK" });
				context.Countries.AddOrUpdate(new Country { Name = "Costa Rica", TwoLetterCountryCode = "CR", ThreeLetterCountryCode = "CRI" });
				context.Countries.AddOrUpdate(new Country { Name = "Cote D''ivoire", TwoLetterCountryCode = "CI", ThreeLetterCountryCode = "CIV" });
				context.Countries.AddOrUpdate(new Country { Name = "Croatia (Local Name: Hrvatska)", TwoLetterCountryCode = "HR", ThreeLetterCountryCode = "HRV" });
				context.Countries.AddOrUpdate(new Country { Name = "Cuba", TwoLetterCountryCode = "CU", ThreeLetterCountryCode = "CUB" });
				context.Countries.AddOrUpdate(new Country { Name = "Cyprus", TwoLetterCountryCode = "CY", ThreeLetterCountryCode = "CYP" });
				context.Countries.AddOrUpdate(new Country { Name = "Czech Republic", TwoLetterCountryCode = "CZ", ThreeLetterCountryCode = "CZE" });
				context.Countries.AddOrUpdate(new Country { Name = "Denmark", TwoLetterCountryCode = "DK", ThreeLetterCountryCode = "DNK" });
				context.Countries.AddOrUpdate(new Country { Name = "Djibouti", TwoLetterCountryCode = "DJ", ThreeLetterCountryCode = "DJI" });
				context.Countries.AddOrUpdate(new Country { Name = "Dominica", TwoLetterCountryCode = "DM", ThreeLetterCountryCode = "DMA" });
				context.Countries.AddOrUpdate(new Country { Name = "Dominican Republic", TwoLetterCountryCode = "DO", ThreeLetterCountryCode = "DOM" });
				context.Countries.AddOrUpdate(new Country { Name = "East Timor", TwoLetterCountryCode = "TP", ThreeLetterCountryCode = "TMP" });
				context.Countries.AddOrUpdate(new Country { Name = "Ecuador", TwoLetterCountryCode = "EC", ThreeLetterCountryCode = "ECU" });
				context.Countries.AddOrUpdate(new Country { Name = "Egypt", TwoLetterCountryCode = "EG", ThreeLetterCountryCode = "EGY" });
				context.Countries.AddOrUpdate(new Country { Name = "El Salvador", TwoLetterCountryCode = "SV", ThreeLetterCountryCode = "SLV" });
				context.Countries.AddOrUpdate(new Country { Name = "Equatorial Guinea", TwoLetterCountryCode = "GQ", ThreeLetterCountryCode = "GNQ" });
				context.Countries.AddOrUpdate(new Country { Name = "Eritrea", TwoLetterCountryCode = "ER", ThreeLetterCountryCode = "ERI" });
				context.Countries.AddOrUpdate(new Country { Name = "Estonia", TwoLetterCountryCode = "EE", ThreeLetterCountryCode = "EST" });
				context.Countries.AddOrUpdate(new Country { Name = "Ethiopia", TwoLetterCountryCode = "ET", ThreeLetterCountryCode = "ETH" });
				context.Countries.AddOrUpdate(new Country { Name = "Falkland Islands (Malvinas)", TwoLetterCountryCode = "FK", ThreeLetterCountryCode = "FLK" });
				context.Countries.AddOrUpdate(new Country { Name = "Faroe Islands", TwoLetterCountryCode = "FO", ThreeLetterCountryCode = "FRO" });
				context.Countries.AddOrUpdate(new Country { Name = "Fiji", TwoLetterCountryCode = "FJ", ThreeLetterCountryCode = "FJI" });
				context.Countries.AddOrUpdate(new Country { Name = "Finland", TwoLetterCountryCode = "FI", ThreeLetterCountryCode = "FIN" });
				context.Countries.AddOrUpdate(new Country { Name = "France", TwoLetterCountryCode = "FR", ThreeLetterCountryCode = "FRA" });
				context.Countries.AddOrUpdate(new Country { Name = "France, Metropolitan", TwoLetterCountryCode = "FX", ThreeLetterCountryCode = "FXX" });
				context.Countries.AddOrUpdate(new Country { Name = "French Guiana", TwoLetterCountryCode = "GF", ThreeLetterCountryCode = "GUF" });
				context.Countries.AddOrUpdate(new Country { Name = "French Polynesia", TwoLetterCountryCode = "PF", ThreeLetterCountryCode = "PYF" });
				context.Countries.AddOrUpdate(new Country { Name = "French Southern Territories", TwoLetterCountryCode = "TF", ThreeLetterCountryCode = "ATF" });
				context.Countries.AddOrUpdate(new Country { Name = "Gabon", TwoLetterCountryCode = "GA", ThreeLetterCountryCode = "GAB" });
				context.Countries.AddOrUpdate(new Country { Name = "Gambia", TwoLetterCountryCode = "GM", ThreeLetterCountryCode = "GMB" });
				context.Countries.AddOrUpdate(new Country { Name = "Georgia", TwoLetterCountryCode = "GE", ThreeLetterCountryCode = "GEO" });
				context.Countries.AddOrUpdate(new Country { Name = "Germany", TwoLetterCountryCode = "DE", ThreeLetterCountryCode = "DEU" });
				context.Countries.AddOrUpdate(new Country { Name = "Ghana", TwoLetterCountryCode = "GH", ThreeLetterCountryCode = "GHA" });
				context.Countries.AddOrUpdate(new Country { Name = "Gibraltar", TwoLetterCountryCode = "GI", ThreeLetterCountryCode = "GIB" });
				context.Countries.AddOrUpdate(new Country { Name = "Greece", TwoLetterCountryCode = "GR", ThreeLetterCountryCode = "GRC" });
				context.Countries.AddOrUpdate(new Country { Name = "Greenland", TwoLetterCountryCode = "GL", ThreeLetterCountryCode = "GRL" });
				context.Countries.AddOrUpdate(new Country { Name = "Grenada", TwoLetterCountryCode = "GD", ThreeLetterCountryCode = "GRD" });
				context.Countries.AddOrUpdate(new Country { Name = "Guadeloupe", TwoLetterCountryCode = "GP", ThreeLetterCountryCode = "GLP" });
				context.Countries.AddOrUpdate(new Country { Name = "Guam", TwoLetterCountryCode = "GU", ThreeLetterCountryCode = "GUM" });
				context.Countries.AddOrUpdate(new Country { Name = "Guatemala", TwoLetterCountryCode = "GT", ThreeLetterCountryCode = "GTM" });
				context.Countries.AddOrUpdate(new Country { Name = "Guinea", TwoLetterCountryCode = "GN", ThreeLetterCountryCode = "GIN" });
				context.Countries.AddOrUpdate(new Country { Name = "Guinea-bissau", TwoLetterCountryCode = "GW", ThreeLetterCountryCode = "GNB" });
				context.Countries.AddOrUpdate(new Country { Name = "Guyana", TwoLetterCountryCode = "GY", ThreeLetterCountryCode = "GUY" });
				context.Countries.AddOrUpdate(new Country { Name = "Haiti", TwoLetterCountryCode = "HT", ThreeLetterCountryCode = "HTI" });
				context.Countries.AddOrUpdate(new Country { Name = "Heard And Mc Donald Islands", TwoLetterCountryCode = "HM", ThreeLetterCountryCode = "HMD" });
				context.Countries.AddOrUpdate(new Country { Name = "Holy See (Vatican City State)", TwoLetterCountryCode = "VA", ThreeLetterCountryCode = "VAT" });
				context.Countries.AddOrUpdate(new Country { Name = "Honduras", TwoLetterCountryCode = "HN", ThreeLetterCountryCode = "HND" });
				context.Countries.AddOrUpdate(new Country { Name = "Hong Kong", TwoLetterCountryCode = "HK", ThreeLetterCountryCode = "HKG" });
				context.Countries.AddOrUpdate(new Country { Name = "Hungary", TwoLetterCountryCode = "HU", ThreeLetterCountryCode = "HUN" });
				context.Countries.AddOrUpdate(new Country { Name = "Iceland", TwoLetterCountryCode = "IS", ThreeLetterCountryCode = "ISL" });
				context.Countries.AddOrUpdate(new Country { Name = "India", TwoLetterCountryCode = "IN", ThreeLetterCountryCode = "IND" });
				context.Countries.AddOrUpdate(new Country { Name = "Indonesia", TwoLetterCountryCode = "ID", ThreeLetterCountryCode = "IDN" });
				context.Countries.AddOrUpdate(new Country { Name = "Iran (Islamic Republic Of)", TwoLetterCountryCode = "IR", ThreeLetterCountryCode = "IRN" });
				context.Countries.AddOrUpdate(new Country { Name = "Iraq", TwoLetterCountryCode = "IQ", ThreeLetterCountryCode = "IRQ" });
				context.Countries.AddOrUpdate(new Country { Name = "Ireland", TwoLetterCountryCode = "IE", ThreeLetterCountryCode = "IRL" });
				context.Countries.AddOrUpdate(new Country { Name = "Israel", TwoLetterCountryCode = "IL", ThreeLetterCountryCode = "ISR" });
				context.Countries.AddOrUpdate(new Country { Name = "Italy", TwoLetterCountryCode = "IT", ThreeLetterCountryCode = "ITA" });
				context.Countries.AddOrUpdate(new Country { Name = "Jamaica", TwoLetterCountryCode = "JM", ThreeLetterCountryCode = "JAM" });
				context.Countries.AddOrUpdate(new Country { Name = "Japan", TwoLetterCountryCode = "JP", ThreeLetterCountryCode = "JPN" });
				context.Countries.AddOrUpdate(new Country { Name = "Jordan", TwoLetterCountryCode = "JO", ThreeLetterCountryCode = "JOR" });
				context.Countries.AddOrUpdate(new Country { Name = "Kazakhstan", TwoLetterCountryCode = "KZ", ThreeLetterCountryCode = "KAZ" });
				context.Countries.AddOrUpdate(new Country { Name = "Kenya", TwoLetterCountryCode = "KE", ThreeLetterCountryCode = "KEN" });
				context.Countries.AddOrUpdate(new Country { Name = "Kiribati", TwoLetterCountryCode = "KI", ThreeLetterCountryCode = "KIR" });
				context.Countries.AddOrUpdate(new Country { Name = "Korea, D.P.R.O.", TwoLetterCountryCode = "KP", ThreeLetterCountryCode = "PRK" });
				context.Countries.AddOrUpdate(new Country { Name = "Korea, Republic Of", TwoLetterCountryCode = "KR", ThreeLetterCountryCode = "KOR" });
				context.Countries.AddOrUpdate(new Country { Name = "Kuwait", TwoLetterCountryCode = "KW", ThreeLetterCountryCode = "KWT" });
				context.Countries.AddOrUpdate(new Country { Name = "Kyrgyzstan", TwoLetterCountryCode = "KG", ThreeLetterCountryCode = "KGZ" });
				context.Countries.AddOrUpdate(new Country { Name = "Laos", TwoLetterCountryCode = "LA", ThreeLetterCountryCode = "LAO" });
				context.Countries.AddOrUpdate(new Country { Name = "Latvia", TwoLetterCountryCode = "LV", ThreeLetterCountryCode = "LVA" });
				context.Countries.AddOrUpdate(new Country { Name = "Lebanon", TwoLetterCountryCode = "LB", ThreeLetterCountryCode = "LBN" });
				context.Countries.AddOrUpdate(new Country { Name = "Lesotho", TwoLetterCountryCode = "LS", ThreeLetterCountryCode = "LSO" });
				context.Countries.AddOrUpdate(new Country { Name = "Liberia", TwoLetterCountryCode = "LR", ThreeLetterCountryCode = "LBR" });
				context.Countries.AddOrUpdate(new Country { Name = "Libyan Arab Jamahiriya", TwoLetterCountryCode = "LY", ThreeLetterCountryCode = "LBY" });
				context.Countries.AddOrUpdate(new Country { Name = "Liechtenstein", TwoLetterCountryCode = "LI", ThreeLetterCountryCode = "LIE" });
				context.Countries.AddOrUpdate(new Country { Name = "Lithuania", TwoLetterCountryCode = "LT", ThreeLetterCountryCode = "LTU" });
				context.Countries.AddOrUpdate(new Country { Name = "Luxembourg", TwoLetterCountryCode = "LU", ThreeLetterCountryCode = "LUX" });
				context.Countries.AddOrUpdate(new Country { Name = "Macau", TwoLetterCountryCode = "MO", ThreeLetterCountryCode = "MAC" });
				context.Countries.AddOrUpdate(new Country { Name = "Macedonia", TwoLetterCountryCode = "MK", ThreeLetterCountryCode = "MKD" });
				context.Countries.AddOrUpdate(new Country { Name = "Madagascar", TwoLetterCountryCode = "MG", ThreeLetterCountryCode = "MDG" });
				context.Countries.AddOrUpdate(new Country { Name = "Malawi", TwoLetterCountryCode = "MW", ThreeLetterCountryCode = "MWI" });
				context.Countries.AddOrUpdate(new Country { Name = "Malaysia", TwoLetterCountryCode = "MY", ThreeLetterCountryCode = "MYS" });
				context.Countries.AddOrUpdate(new Country { Name = "Maldives", TwoLetterCountryCode = "MV", ThreeLetterCountryCode = "MDV" });
				context.Countries.AddOrUpdate(new Country { Name = "Mali", TwoLetterCountryCode = "ML", ThreeLetterCountryCode = "MLI" });
				context.Countries.AddOrUpdate(new Country { Name = "Malta", TwoLetterCountryCode = "MT", ThreeLetterCountryCode = "MLT" });
				context.Countries.AddOrUpdate(new Country { Name = "Marshall Islands", TwoLetterCountryCode = "MH", ThreeLetterCountryCode = "MHL" });
				context.Countries.AddOrUpdate(new Country { Name = "Martinique", TwoLetterCountryCode = "MQ", ThreeLetterCountryCode = "MTQ" });
				context.Countries.AddOrUpdate(new Country { Name = "Mauritania", TwoLetterCountryCode = "MR", ThreeLetterCountryCode = "MRT" });
				context.Countries.AddOrUpdate(new Country { Name = "Mauritius", TwoLetterCountryCode = "MU", ThreeLetterCountryCode = "MUS" });
				context.Countries.AddOrUpdate(new Country { Name = "Mayotte", TwoLetterCountryCode = "YT", ThreeLetterCountryCode = "MYT" });
				context.Countries.AddOrUpdate(new Country { Name = "Mexico", TwoLetterCountryCode = "MX", ThreeLetterCountryCode = "MEX" });
				context.Countries.AddOrUpdate(new Country { Name = "Micronesia, Federated States Of", TwoLetterCountryCode = "FM", ThreeLetterCountryCode = "FSM" });
				context.Countries.AddOrUpdate(new Country { Name = "Moldova, Republic Of", TwoLetterCountryCode = "MD", ThreeLetterCountryCode = "MDA" });
				context.Countries.AddOrUpdate(new Country { Name = "Monaco", TwoLetterCountryCode = "MC", ThreeLetterCountryCode = "MCO" });
				context.Countries.AddOrUpdate(new Country { Name = "Mongolia", TwoLetterCountryCode = "MN", ThreeLetterCountryCode = "MNG" });
				context.Countries.AddOrUpdate(new Country { Name = "Montenegro", TwoLetterCountryCode = "ME", ThreeLetterCountryCode = "MNE" });
				context.Countries.AddOrUpdate(new Country { Name = "Montserrat", TwoLetterCountryCode = "MS", ThreeLetterCountryCode = "MSR" });
				context.Countries.AddOrUpdate(new Country { Name = "Morocco", TwoLetterCountryCode = "MA", ThreeLetterCountryCode = "MAR" });
				context.Countries.AddOrUpdate(new Country { Name = "Mozambique", TwoLetterCountryCode = "MZ", ThreeLetterCountryCode = "MOZ" });
				context.Countries.AddOrUpdate(new Country { Name = "Myanmar (Burma)", TwoLetterCountryCode = "MM", ThreeLetterCountryCode = "MMR" });
				context.Countries.AddOrUpdate(new Country { Name = "Namibia", TwoLetterCountryCode = "NA", ThreeLetterCountryCode = "NAM" });
				context.Countries.AddOrUpdate(new Country { Name = "Nauru", TwoLetterCountryCode = "NR", ThreeLetterCountryCode = "NRU" });
				context.Countries.AddOrUpdate(new Country { Name = "Nepal", TwoLetterCountryCode = "NP", ThreeLetterCountryCode = "NPL" });
				context.Countries.AddOrUpdate(new Country { Name = "Netherlands", TwoLetterCountryCode = "NL", ThreeLetterCountryCode = "NLD" });
				context.Countries.AddOrUpdate(new Country { Name = "Netherlands Antilles", TwoLetterCountryCode = "AN", ThreeLetterCountryCode = "ANT" });
				context.Countries.AddOrUpdate(new Country { Name = "New Caledonia", TwoLetterCountryCode = "NC", ThreeLetterCountryCode = "NCL" });
				context.Countries.AddOrUpdate(new Country { Name = "New Zealand", TwoLetterCountryCode = "NZ", ThreeLetterCountryCode = "NZL" });
				context.Countries.AddOrUpdate(new Country { Name = "Nicaragua", TwoLetterCountryCode = "NI", ThreeLetterCountryCode = "NIC" });
				context.Countries.AddOrUpdate(new Country { Name = "Niger", TwoLetterCountryCode = "NE", ThreeLetterCountryCode = "NER" });
				context.Countries.AddOrUpdate(new Country { Name = "Nigeria", TwoLetterCountryCode = "NG", ThreeLetterCountryCode = "NGA" });
				context.Countries.AddOrUpdate(new Country { Name = "Niue", TwoLetterCountryCode = "NU", ThreeLetterCountryCode = "NIU" });
				context.Countries.AddOrUpdate(new Country { Name = "Norfolk Island", TwoLetterCountryCode = "NF", ThreeLetterCountryCode = "NFK" });
				context.Countries.AddOrUpdate(new Country { Name = "Northern Mariana Islands", TwoLetterCountryCode = "MP", ThreeLetterCountryCode = "MNP" });
				context.Countries.AddOrUpdate(new Country { Name = "Norway", TwoLetterCountryCode = "NO", ThreeLetterCountryCode = "NOR" });
				context.Countries.AddOrUpdate(new Country { Name = "Oman", TwoLetterCountryCode = "OM", ThreeLetterCountryCode = "OMN" });
				context.Countries.AddOrUpdate(new Country { Name = "Pakistan", TwoLetterCountryCode = "PK", ThreeLetterCountryCode = "PAK" });
				context.Countries.AddOrUpdate(new Country { Name = "Palau", TwoLetterCountryCode = "PW", ThreeLetterCountryCode = "PLW" });
				context.Countries.AddOrUpdate(new Country { Name = "Panama", TwoLetterCountryCode = "PA", ThreeLetterCountryCode = "PAN" });
				context.Countries.AddOrUpdate(new Country { Name = "Papua New Guinea", TwoLetterCountryCode = "PG", ThreeLetterCountryCode = "PNG" });
				context.Countries.AddOrUpdate(new Country { Name = "Paraguay", TwoLetterCountryCode = "PY", ThreeLetterCountryCode = "PRY" });
				context.Countries.AddOrUpdate(new Country { Name = "Peru", TwoLetterCountryCode = "PE", ThreeLetterCountryCode = "PER" });
				context.Countries.AddOrUpdate(new Country { Name = "Philippines", TwoLetterCountryCode = "PH", ThreeLetterCountryCode = "PHL" });
				context.Countries.AddOrUpdate(new Country { Name = "Pitcairn", TwoLetterCountryCode = "PN", ThreeLetterCountryCode = "PCN" });
				context.Countries.AddOrUpdate(new Country { Name = "Poland", TwoLetterCountryCode = "PL", ThreeLetterCountryCode = "POL" });
				context.Countries.AddOrUpdate(new Country { Name = "Portugal", TwoLetterCountryCode = "PT", ThreeLetterCountryCode = "PRT" });
				context.Countries.AddOrUpdate(new Country { Name = "Puerto Rico", TwoLetterCountryCode = "PR", ThreeLetterCountryCode = "PRI" });
				context.Countries.AddOrUpdate(new Country { Name = "Qatar", TwoLetterCountryCode = "QA", ThreeLetterCountryCode = "QAT" });
				context.Countries.AddOrUpdate(new Country { Name = "Reunion", TwoLetterCountryCode = "RE", ThreeLetterCountryCode = "REU" });
				context.Countries.AddOrUpdate(new Country { Name = "Romania", TwoLetterCountryCode = "RO", ThreeLetterCountryCode = "ROM" });
				context.Countries.AddOrUpdate(new Country { Name = "Russian Federation", TwoLetterCountryCode = "RU", ThreeLetterCountryCode = "RUS" });
				context.Countries.AddOrUpdate(new Country { Name = "Rwanda", TwoLetterCountryCode = "RW", ThreeLetterCountryCode = "RWA" });
				context.Countries.AddOrUpdate(new Country { Name = "Saint Kitts And Nevis", TwoLetterCountryCode = "KN", ThreeLetterCountryCode = "KNA" });
				context.Countries.AddOrUpdate(new Country { Name = "Saint Lucia", TwoLetterCountryCode = "LC", ThreeLetterCountryCode = "LCA" });
				context.Countries.AddOrUpdate(new Country { Name = "Saint Vincent And The Grenadines", TwoLetterCountryCode = "VC", ThreeLetterCountryCode = "VCT" });
				context.Countries.AddOrUpdate(new Country { Name = "Samoa", TwoLetterCountryCode = "WS", ThreeLetterCountryCode = "WSM" });
				context.Countries.AddOrUpdate(new Country { Name = "San Marino", TwoLetterCountryCode = "SM", ThreeLetterCountryCode = "SMR" });
				context.Countries.AddOrUpdate(new Country { Name = "Sao Tome And Principe", TwoLetterCountryCode = "ST", ThreeLetterCountryCode = "STP" });
				context.Countries.AddOrUpdate(new Country { Name = "Saudi Arabia", TwoLetterCountryCode = "SA", ThreeLetterCountryCode = "SAU" });
				context.Countries.AddOrUpdate(new Country { Name = "Senegal", TwoLetterCountryCode = "SN", ThreeLetterCountryCode = "SEN" });
				context.Countries.AddOrUpdate(new Country { Name = "Serbia", TwoLetterCountryCode = "RS", ThreeLetterCountryCode = "SRB" });
				context.Countries.AddOrUpdate(new Country { Name = "Seychelles", TwoLetterCountryCode = "SC", ThreeLetterCountryCode = "SYC" });
				context.Countries.AddOrUpdate(new Country { Name = "Sierra Leone", TwoLetterCountryCode = "SL", ThreeLetterCountryCode = "SLE" });
				context.Countries.AddOrUpdate(new Country { Name = "Singapore", TwoLetterCountryCode = "SG", ThreeLetterCountryCode = "SGP" });
				context.Countries.AddOrUpdate(new Country { Name = "Slovakia (Slovak Republic)", TwoLetterCountryCode = "SK", ThreeLetterCountryCode = "SVK" });
				context.Countries.AddOrUpdate(new Country { Name = "Slovenia", TwoLetterCountryCode = "SI", ThreeLetterCountryCode = "SVN" });
				context.Countries.AddOrUpdate(new Country { Name = "Solomon Islands", TwoLetterCountryCode = "SB", ThreeLetterCountryCode = "SLB" });
				context.Countries.AddOrUpdate(new Country { Name = "Somalia", TwoLetterCountryCode = "SO", ThreeLetterCountryCode = "SOM" });
				context.Countries.AddOrUpdate(new Country { Name = "South Africa", TwoLetterCountryCode = "ZA", ThreeLetterCountryCode = "ZAF" });
				context.Countries.AddOrUpdate(new Country { Name = "South Georgia And South S.S.", TwoLetterCountryCode = "GS", ThreeLetterCountryCode = "SGS" });
				context.Countries.AddOrUpdate(new Country { Name = "South Sudan", TwoLetterCountryCode = "SS", ThreeLetterCountryCode = "SSD" });
				context.Countries.AddOrUpdate(new Country { Name = "Spain", TwoLetterCountryCode = "ES", ThreeLetterCountryCode = "ESP" });
				context.Countries.AddOrUpdate(new Country { Name = "Sri Lanka", TwoLetterCountryCode = "LK", ThreeLetterCountryCode = "LKA" });
				context.Countries.AddOrUpdate(new Country { Name = "St. Helena", TwoLetterCountryCode = "SH", ThreeLetterCountryCode = "SHN" });
				context.Countries.AddOrUpdate(new Country { Name = "St. Pierre And Miquelon", TwoLetterCountryCode = "PM", ThreeLetterCountryCode = "SPM" });
				context.Countries.AddOrUpdate(new Country { Name = "Sudan", TwoLetterCountryCode = "SD", ThreeLetterCountryCode = "SDN" });
				context.Countries.AddOrUpdate(new Country { Name = "Suriname", TwoLetterCountryCode = "SR", ThreeLetterCountryCode = "SUR" });
				context.Countries.AddOrUpdate(new Country { Name = "Svalbard And Jan Mayen Islands", TwoLetterCountryCode = "SJ", ThreeLetterCountryCode = "SJM" });
				context.Countries.AddOrUpdate(new Country { Name = "Swaziland", TwoLetterCountryCode = "SZ", ThreeLetterCountryCode = "SWZ" });
				context.Countries.AddOrUpdate(new Country { Name = "Sweden", TwoLetterCountryCode = "SE", ThreeLetterCountryCode = "SWE" });
				context.Countries.AddOrUpdate(new Country { Name = "Switzerland", TwoLetterCountryCode = "CH", ThreeLetterCountryCode = "CHE" });
				context.Countries.AddOrUpdate(new Country { Name = "Syrian Arab Republic", TwoLetterCountryCode = "SY", ThreeLetterCountryCode = "SYR" });
				context.Countries.AddOrUpdate(new Country { Name = "Taiwan, Province Of China", TwoLetterCountryCode = "TW", ThreeLetterCountryCode = "TWN" });
				context.Countries.AddOrUpdate(new Country { Name = "Tajikistan", TwoLetterCountryCode = "TJ", ThreeLetterCountryCode = "TJK" });
				context.Countries.AddOrUpdate(new Country { Name = "Tanzania, United Republic Of", TwoLetterCountryCode = "TZ", ThreeLetterCountryCode = "TZA" });
				context.Countries.AddOrUpdate(new Country { Name = "Thailand", TwoLetterCountryCode = "TH", ThreeLetterCountryCode = "THA" });
				context.Countries.AddOrUpdate(new Country { Name = "Togo", TwoLetterCountryCode = "TG", ThreeLetterCountryCode = "TGO" });
				context.Countries.AddOrUpdate(new Country { Name = "Tokelau", TwoLetterCountryCode = "TK", ThreeLetterCountryCode = "TKL" });
				context.Countries.AddOrUpdate(new Country { Name = "Tonga", TwoLetterCountryCode = "TO", ThreeLetterCountryCode = "TON" });
				context.Countries.AddOrUpdate(new Country { Name = "Trinidad And Tobago", TwoLetterCountryCode = "TT", ThreeLetterCountryCode = "TTO" });
				context.Countries.AddOrUpdate(new Country { Name = "Tunisia", TwoLetterCountryCode = "TN", ThreeLetterCountryCode = "TUN" });
				context.Countries.AddOrUpdate(new Country { Name = "Turkey", TwoLetterCountryCode = "TR", ThreeLetterCountryCode = "TUR" });
				context.Countries.AddOrUpdate(new Country { Name = "Turkmenistan", TwoLetterCountryCode = "TM", ThreeLetterCountryCode = "TKM" });
				context.Countries.AddOrUpdate(new Country { Name = "Turks And Caicos Islands", TwoLetterCountryCode = "TC", ThreeLetterCountryCode = "TCA" });
				context.Countries.AddOrUpdate(new Country { Name = "Tuvalu", TwoLetterCountryCode = "TV", ThreeLetterCountryCode = "TUV" });
				context.Countries.AddOrUpdate(new Country { Name = "U.s. Minor Islands", TwoLetterCountryCode = "UM", ThreeLetterCountryCode = "UMI" });
				context.Countries.AddOrUpdate(new Country { Name = "Uganda", TwoLetterCountryCode = "UG", ThreeLetterCountryCode = "UGA" });
				context.Countries.AddOrUpdate(new Country { Name = "Ukraine", TwoLetterCountryCode = "UA", ThreeLetterCountryCode = "UKR" });
				context.Countries.AddOrUpdate(new Country { Name = "United Arab Emirates", TwoLetterCountryCode = "AE", ThreeLetterCountryCode = "ARE" });
				context.Countries.AddOrUpdate(new Country { Name = "United Kingdom", TwoLetterCountryCode = "GB", ThreeLetterCountryCode = "GBR" });
				context.Countries.AddOrUpdate(new Country { Name = "United States", TwoLetterCountryCode = "US", ThreeLetterCountryCode = "USA" });
				context.Countries.AddOrUpdate(new Country { Name = "Uruguay", TwoLetterCountryCode = "UY", ThreeLetterCountryCode = "URY" });
				context.Countries.AddOrUpdate(new Country { Name = "Uzbekistan", TwoLetterCountryCode = "UZ", ThreeLetterCountryCode = "UZB" });
				context.Countries.AddOrUpdate(new Country { Name = "Vanuatu", TwoLetterCountryCode = "VU", ThreeLetterCountryCode = "VUT" });
				context.Countries.AddOrUpdate(new Country { Name = "Venezuela", TwoLetterCountryCode = "VE", ThreeLetterCountryCode = "VEN" });
				context.Countries.AddOrUpdate(new Country { Name = "Viet Nam", TwoLetterCountryCode = "VN", ThreeLetterCountryCode = "VNM" });
				context.Countries.AddOrUpdate(new Country { Name = "Virgin Islands (British)", TwoLetterCountryCode = "VG", ThreeLetterCountryCode = "VGB" });
				context.Countries.AddOrUpdate(new Country { Name = "Virgin Islands (U.S.)", TwoLetterCountryCode = "VI", ThreeLetterCountryCode = "VIR" });
				context.Countries.AddOrUpdate(new Country { Name = "Wallis And Futuna Islands", TwoLetterCountryCode = "WF", ThreeLetterCountryCode = "WLF" });
				context.Countries.AddOrUpdate(new Country { Name = "Western Sahara", TwoLetterCountryCode = "EH", ThreeLetterCountryCode = "ESH" });
				context.Countries.AddOrUpdate(new Country { Name = "Yemen", TwoLetterCountryCode = "YE", ThreeLetterCountryCode = "YEM" });
				context.Countries.AddOrUpdate(new Country { Name = "Zambia", TwoLetterCountryCode = "ZM", ThreeLetterCountryCode = "ZMB" });
				context.Countries.AddOrUpdate(new Country { Name = "Zimbabwe", TwoLetterCountryCode = "ZW", ThreeLetterCountryCode = "ZWE" });
			}
		}

	}
}
