//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K9.Globalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K9.Globalisation.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Donated.
        /// </summary>
        public static string AmountDonatedLabel {
            get {
                return ResourceManager.GetString("AmountDonatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would like to donate:.
        /// </summary>
        public static string AmountToDonateLabel {
            get {
                return ResourceManager.GetString("AmountToDonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is under development and new features are being added continuously. Your feedback is welcome. Please visit the support page to get in touch..
        /// </summary>
        public static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessings.
        /// </summary>
        public static string Blessings {
            get {
                return ResourceManager.GetString("Blessings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Green.
        /// </summary>
        public static string BrightGreen {
            get {
                return ResourceManager.GetString("BrightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Your Nine Star Ki Energy.
        /// </summary>
        public static string CalculateYourNineStarKi {
            get {
                return ResourceManager.GetString("CalculateYourNineStarKi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string Centre {
            get {
                return ResourceManager.GetString("Centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Amount.
        /// </summary>
        public static string ChangeAmount {
            get {
                return ResourceManager.GetString("ChangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character / Emotional Energy.
        /// </summary>
        public static string CharacterEnergyLabel {
            get {
                return ResourceManager.GetString("CharacterEnergyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chen.
        /// </summary>
        public static string Chen {
            get {
                return ResourceManager.GetString("Chen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch&apos;ien.
        /// </summary>
        public static string Chien {
            get {
                return ResourceManager.GetString("Chien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Childhood.
        /// </summary>
        public static string ChildhoodLabel {
            get {
                return ResourceManager.GetString("ChildhoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Colour {
            get {
                return ResourceManager.GetString("Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NineStar has been created to share knowledge about the ancient wisdom of nine star ki astrology to help people gain a better understanding of themselves and of their loved ones, as well as the many cycles that affect their lives..
        /// </summary>
        public static string CompanyBlurbFooter {
            get {
                return ResourceManager.GetString("CompanyBlurbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star ki is an ancient system of astrology, largely uknown in the west, but slowly regaining popularity. It is deeper and more extensive than the zodiac and can offer some quite astonishing insights into our nature and the many cyles that influence our lives..
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompanyLegalDescription {
            get {
                return ResourceManager.GetString("CompanyLegalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website created to share knowledge about the ancient widsom of nine star ki astrology..
        /// </summary>
        public static string CompanyShortDescription {
            get {
                return ResourceManager.GetString("CompanyShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Earth.
        /// </summary>
        public static string CoreEarth {
            get {
                return ResourceManager.GetString("CoreEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string coreearth_description {
            get {
                return ResourceManager.GetString("coreearth_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string coreearth_trigram {
            get {
                return ResourceManager.GetString("coreearth_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Email Address.
        /// </summary>
        public static string CustomerEmailLabel {
            get {
                return ResourceManager.GetString("CustomerEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerLabel {
            get {
                return ResourceManager.GetString("CustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirthLabel {
            get {
                return ResourceManager.GetString("DateOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated On.
        /// </summary>
        public static string DonatedOnLabel {
            get {
                return ResourceManager.GetString("DonatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much would you like to donate?.
        /// </summary>
        public static string DonationAmountLabel {
            get {
                return ResourceManager.GetString("DonationAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making a donation to NineStar will make a big impact on our ability to continue to provide and develop this invaluable service. We are tremendously grateful for your support..
        /// </summary>
        public static string DonationBlurb {
            get {
                return ResourceManager.GetString("DonationBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///        padding: 0;
        ///        font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///        font-size: 100%;
        ///        text-rendering: optimizeLegibility !important;
        ///        -webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///&lt;p class=&quot;text&quot;&gt;Dear Team,&lt;/p&gt;
        ///&lt;p class=&quot;text&quot;&gt;We have received a do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DonationReceivedEmail {
            get {
                return ResourceManager.GetString("DonationReceivedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        public static string Donations {
            get {
                return ResourceManager.GetString("Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your donation was received. Thank you!.
        /// </summary>
        public static string DonationSuccessful {
            get {
                return ResourceManager.GetString("DonationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Received.
        /// </summary>
        public static string DonationSuccessfulTitle {
            get {
                return ResourceManager.GetString("DonationSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation To.
        /// </summary>
        public static string DonationTo {
            get {
                return ResourceManager.GetString("DonationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation To NineStar.
        /// </summary>
        public static string DonationToNineStar {
            get {
                return ResourceManager.GetString("DonationToNineStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eldest Daughter.
        /// </summary>
        public static string EldestDaughter {
            get {
                return ResourceManager.GetString("EldestDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eldest Son.
        /// </summary>
        public static string EldestSon {
            get {
                return ResourceManager.GetString("EldestSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Description.
        /// </summary>
        public static string EnergyDescriptionLabel {
            get {
                return ResourceManager.GetString("EnergyDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enerty Type.
        /// </summary>
        public static string EnergyTypeLabel {
            get {
                return ResourceManager.GetString("EnergyTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string ExamplesLabel {
            get {
                return ResourceManager.GetString("ExamplesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Member.
        /// </summary>
        public static string FamilyMember {
            get {
                return ResourceManager.GetString("FamilyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string fire_description {
            get {
                return ResourceManager.GetString("fire_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string fire_trigram {
            get {
                return ResourceManager.GetString("fire_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string HealthLabel {
            get {
                return ResourceManager.GetString("HealthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heaven.
        /// </summary>
        public static string Heaven {
            get {
                return ResourceManager.GetString("Heaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string heaven_description {
            get {
                return ResourceManager.GetString("heaven_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string heaven_trigram {
            get {
                return ResourceManager.GetString("heaven_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermaphrodite.
        /// </summary>
        public static string Hermaphrodite {
            get {
                return ResourceManager.GetString("Hermaphrodite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K&apos;An.
        /// </summary>
        public static string Kan {
            get {
                return ResourceManager.GetString("Kan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ken.
        /// </summary>
        public static string Ken {
            get {
                return ResourceManager.GetString("Ken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star ki astrology horoscope love relationships.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K&apos;Un.
        /// </summary>
        public static string Kun {
            get {
                return ResourceManager.GetString("Kun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake.
        /// </summary>
        public static string Lake {
            get {
                return ResourceManager.GetString("Lake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string lake_description {
            get {
                return ResourceManager.GetString("lake_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string lake_trigram {
            get {
                return ResourceManager.GetString("lake_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li.
        /// </summary>
        public static string Li {
            get {
                return ResourceManager.GetString("Li", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Energy.
        /// </summary>
        public static string MainEnergy {
            get {
                return ResourceManager.GetString("MainEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Energy.
        /// </summary>
        public static string MainEnergyLabel {
            get {
                return ResourceManager.GetString("MainEnergyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        public static string MainTitleLeft {
            get {
                return ResourceManager.GetString("MainTitleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string MainTitleRight {
            get {
                return ResourceManager.GetString("MainTitleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Donation.
        /// </summary>
        public static string MakeDonation {
            get {
                return ResourceManager.GetString("MakeDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string Metal {
            get {
                return ResourceManager.GetString("Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Daughter.
        /// </summary>
        public static string MiddleDaughter {
            get {
                return ResourceManager.GetString("MiddleDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Son.
        /// </summary>
        public static string MiddleSon {
            get {
                return ResourceManager.GetString("MiddleSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain.
        /// </summary>
        public static string Mountain {
            get {
                return ResourceManager.GetString("Mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string mountain_description {
            get {
                return ResourceManager.GetString("mountain_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string mountain_trigram {
            get {
                return ResourceManager.GetString("mountain_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string nine_star_ki_title {
            get {
                return ResourceManager.GetString("nine_star_ki_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 Star Ki.
        /// </summary>
        public static string NineStarKiTitle {
            get {
                return ResourceManager.GetString("NineStarKiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northeast.
        /// </summary>
        public static string NorthEast {
            get {
                return ResourceManager.GetString("NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest.
        /// </summary>
        public static string NorthWest {
            get {
                return ResourceManager.GetString("NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupations.
        /// </summary>
        public static string OccupationsLabel {
            get {
                return ResourceManager.GetString("OccupationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On The Brink Of Extinction.
        /// </summary>
        public static string OnTheBrinkOfExtinctionTitle {
            get {
                return ResourceManager.GetString("OnTheBrinkOfExtinctionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Your password has been reset. Please [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PasswordResetEmail {
            get {
                return ResourceManager.GetString("PasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Development.
        /// </summary>
        public static string PersonalDevelopemntLabel {
            get {
                return ResourceManager.GetString("PersonalDevelopemntLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions.
        /// </summary>
        public static string Predictions {
            get {
                return ResourceManager.GetString("Predictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rising Energy.
        /// </summary>
        public static string RisingEnergyLabel {
            get {
                return ResourceManager.GetString("RisingEnergyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventh Child.
        /// </summary>
        public static string SeventhChild {
            get {
                return ResourceManager.GetString("SeventhChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil.
        /// </summary>
        public static string Soil {
            get {
                return ResourceManager.GetString("Soil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string soil_description {
            get {
                return ResourceManager.GetString("soil_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string soil_trigram {
            get {
                return ResourceManager.GetString("soil_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southeast.
        /// </summary>
        public static string SouthEast {
            get {
                return ResourceManager.GetString("SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southwest.
        /// </summary>
        public static string SouthWest {
            get {
                return ResourceManager.GetString("SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Puppydog Software&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    .text
        ///    {{
        ///        font-family: lucida grande, Segoe UI, arial, verdana, lucida sans unicode, tahoma, sans-serif; 
        ///        margin: 0; 
        ///        font-size: 10pt; 
        ///        color: #333399;
        ///        padding-bottom: 12px;
        ///    }}
        ///    .title
        ///    {{
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SupportQuery {
            get {
                return ResourceManager.GetString("SupportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder.
        /// </summary>
        public static string Thunder {
            get {
                return ResourceManager.GetString("Thunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string thunder_description {
            get {
                return ResourceManager.GetString("thunder_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string thunder_trigram {
            get {
                return ResourceManager.GetString("thunder_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Female.
        /// </summary>
        public static string TransFemale {
            get {
                return ResourceManager.GetString("TransFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Male.
        /// </summary>
        public static string TransMale {
            get {
                return ResourceManager.GetString("TransMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigram.
        /// </summary>
        public static string Trigram {
            get {
                return ResourceManager.GetString("Trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigram Interpretation.
        /// </summary>
        public static string TrigramLabel {
            get {
                return ResourceManager.GetString("TrigramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tui.
        /// </summary>
        public static string Tui {
            get {
                return ResourceManager.GetString("Tui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Like water, this energy can resemble a lively mountain stream or, conversely, a deep lake or ocean. Water energies can be adventurous and vivacious, or quiet, reflective and withdrawn.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Water energies benefit greatly from having a container to structure them, just as the river needs the river banks. Without this, they may tend towards chaos and lack of discipline.
        ///&lt;/p&gt;
        ///&lt;p&gt;Water energies can be very sensitive, intuitive and philosophical. They are often very deep thinkers and can ha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string water_description {
            get {
                return ResourceManager.GetString("water_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One yang line encapsulated by two yin lines. Hidden strength and depth within. symbolic of winter&apos;s apparent dormancy on the surface, whilst beneath major change is taking place..
        /// </summary>
        public static string water_trigram {
            get {
                return ResourceManager.GetString("water_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Thank you for registering with {Comp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeEmail {
            get {
                return ResourceManager.GetString("WelcomeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string wind_description {
            get {
                return ResourceManager.GetString("wind_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string wind_trigram {
            get {
                return ResourceManager.GetString("wind_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yang.
        /// </summary>
        public static string Yang {
            get {
                return ResourceManager.GetString("Yang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yin.
        /// </summary>
        public static string Yin {
            get {
                return ResourceManager.GetString("Yin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yin / Yang.
        /// </summary>
        public static string YinYangLabel {
            get {
                return ResourceManager.GetString("YinYangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youngest Daughter.
        /// </summary>
        public static string YoungestDaughter {
            get {
                return ResourceManager.GetString("YoungestDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youngest Son.
        /// </summary>
        public static string YoungestSon {
            get {
                return ResourceManager.GetString("YoungestSon", resourceCulture);
            }
        }
    }
}
